version: '3'

vars:
  # mise dependent
  __TF_MISE_E: 'mise trust; mise exec --'
  __TF_MISE_E_PWSH: 'mise trust; mise exec -- pwsh -NoProfile -ExecutionPolicy Bypass -Command'
  __TF_MISE_E_PWSH_FILE: 'mise trust; mise exec -- pwsh -NoProfile -ExecutionPolicy Bypass -File'
  # os dependent
  __TF_COMMAND_WRAPPER:
    sh: |
      echo '{{if eq OS "windows"}}powershell -ExecutionPolicy Bypass -Command{{else}}bash -c{{end}}'
  __TF_HEADER_LINE: '=============================================================='
  __TF_SEP: ' '
  __TF_VAR_PREFIX:
    sh: |
      echo "{{if eq OS "windows"}}\${{else}}{{end}}"

tasks:
  # ============================================================================
  # Build Tasks
  # ============================================================================

  build:
    desc: 'Build project'
    cmds:
      - task: print:env
      - cmd: |
          {{.__TF_MISE_E}} npm run build

  # ============================================================================
  # Clean Tasks
  # ============================================================================

  clean:
    desc: 'Clean all build artifacts'
    cmds:
      - cmd: |
          {{.__TF_MISE_E}} npm run clean

  # ============================================================================
  # Code Quality Tasks
  # ============================================================================

  audit-check:
    desc: 'Check for security vulnerabilities in dependencies'
    cmds:
      - |
        {{.__TF_MISE_E}} npm audit --audit-level=moderate || true
    silent: true

  duplicate-check:
    desc: 'Check for duplicate code using jscpd'
    cmds:
      - |
        {{.__TF_MISE_E}} npm run duplicate-check
      - git add .jscpd/jscpd-badge.svg 2>/dev/null || true

  format:
    desc: 'Format code and fix issues'
    cmds:
      - task: format:prettier
      - cmd: echo "Code format completed"

  format:check:
    desc: 'Check code formatting without fixing'
    cmds:
      - task: format:check:prettier
      - cmd: echo "Code format check completed"

  format:check:prettier:
    desc: 'Check code formatting using Prettier'
    cmds:
      - |
        {{.__TF_MISE_E}} npx prettier --check "./**/*.{json,toml,yaml,yml}"
    silent: true

  format:prettier:
    desc: 'Format code using Prettier'
    cmds:
      - |
        {{.__TF_MISE_E}} npx prettier --write "./**/*.{json,toml,yaml,yml}"
    silent: true

  license-check:
    desc: 'Check project license compliance'
    cmds:
      - cmd: npm run license-check

  lint:
    desc: 'Run linter and fix issues'
    cmds:
      - task: lint:eslint
      - cmd: echo "Linting completed"

  lint:check:
    desc: 'Run linter without fixing'
    cmds:
      - task: lint:check:eslint
      - cmd: echo "Linting check completed"

  lint:check:eslint:
    desc: 'Check code using ESLint'
    cmds:
      - |
        {{.__TF_MISE_E}} npx eslint "./**/*.{toml,json,yaml,yml}"
      - echo "- eslint lint check completed"
    silent: true

  lint:eslint:
    desc: 'Lint code using ESLint'
    cmds:
      - |
        {{.__TF_MISE_E}} npx eslint --fix "./**/*.{json,toml,yaml,yml}"
      - echo "- eslint lint completed"
    silent: true

  lint:staged:
    desc: 'Run linter on staged files and fix issues'
    cmds:
      - |
        {{.__TF_MISE_E}} npx -y lint-staged
    silent: true

  # ============================================================================
  # Dependencies
  # ============================================================================

  deps:clean:
    desc: 'Clean all project dependencies'
    cmds:
      - task: deps:clean:mise
      - task: deps:clean:npm

  deps:clean:mise:
    desc: 'Clean Mise dependencies'
    cmds:
      - echo "Cleaning Mise dependencies..."
      - cmd: |
          rm -rf \
            ~/.local/share/mise/installs \
            ~/AppData/mise/installs
      - echo "Mise environment cleaned"

  deps:clean:npm:
    desc: 'Clean NodeJs dependencies'
    cmds:
      - |
        echo "Cleaning NodeJs dependencies..."
        rm -rf node_modules package-lock.json
        echo "NodeJs environment cleaned"

  deps:refresh:
    desc: 'Refresh all project dependencies'
    cmds:
      - task: deps:refresh:mise
      - task: deps:refresh:npm

  deps:refresh:mise:
    desc: 'Refresh all Mise packages (update dependencies)'
    cmds:
      - |
        echo "Refreshing Mise packages..."
        touch mise.lock
        mise trust && mise upgrade
        echo "Packages refreshed"

  deps:refresh:npm:
    desc: 'Refresh all NodeJs packages (update dependencies)'
    cmds:
      - |
        echo "Refreshing NodeJs packages..."
        {{.__TF_MISE_E}} npm outdated \
          && {{.__TF_MISE_E}} npm update \
          && {{.__TF_MISE_E}} npm audit fix
        echo "Packages refreshed"

  deps:sync:
    desc: 'Install all project dependencies'
    cmds:
      - task: deps:sync:mise
      - task: deps:sync:npm

  deps:sync:mise:
    desc: 'Install Mise dependencies'
    cmds:
      - |
        echo "Installing Mise dependencies..."
        touch mise.lock
        mise trust && mise install --yes
        echo "Mise environment ready"

  deps:sync:npm:
    desc: 'Install NodeJs dependencies'
    cmds:
      - |
        echo "Installing NodeJs dependencies..."
        {{.__TF_MISE_E}} npm install
        {{.__TF_MISE_E}} npx husky
        echo "NodeJs environment ready"

  # ============================================================================
  # Development Tools
  # ============================================================================

  run:
    desc: 'Run application'
    deps:
      - task: build
    cmds:
      - cmd: |
          {{.__TF_MISE_E}} npm run start

  # ============================================================================
  # Documentation Tasks
  # ============================================================================

  docs:
    desc: 'Build documentation with TypeDoc'
    cmds:
      - cmd: |
          {{.__TF_MISE_E}} npm run docs

  docs:serve:
    desc: 'Serve documentation locally'
    cmds:
      - cmd: |
          echo "Starting documentation server..."
          echo "Open http://localhost:3000 in your browser"
          {{.__TF_MISE_E}} npm run serve

  # ============================================================================
  # Test Tasks
  # ============================================================================

  test:
    desc: 'Run tests'
    cmds:
      - cmd: |
          {{.__TF_MISE_E}} npm run test

  test:coverage:
    desc: 'Generate test coverage report'
    cmds:
      - cmd: |
          {{.__TF_MISE_E}} npm run test:coverage
    silent: true

  # ============================================================================
  # Utility Tasks
  # ============================================================================

  print:env:
    desc: 'Print current build environment variables'
    cmds:
      - cmd: |
          {{.__TF_MISE_E}} env | sort
        platforms: [darwin, linux]
      - cmd: |
          {{.__TF_MISE_E}} {{ .__TF_SEP
            }}pwsh -Command '$BashPath=(Get-Command bash -ErrorAction SilentlyContinue).Path;{{ .__TF_SEP
              }}if ($BashPath) { & $BashPath -c "env | sort" }{{ .__TF_SEP
              }}else { Get-ChildItem "Env:" | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Value)" } }'
        platforms: [windows]

  # ============================================================================
  # Validation Tasks
  # ============================================================================

  validate:
    desc: 'Run CI pipeline for validation'
    cmds:
      - task: format
      - task: clean
      - task: build
      - task: lint
      - task: run
      - task: clean
      - task: test
      - task: docs
      - cmd: |
          echo ""
          echo "{{.__TF_HEADER_LINE}}"
          echo "Validation successful"
          echo "{{.__TF_HEADER_LINE}}"
          echo ""
    silent: true
